### ISSUE TITLE
Configurar Binder para los notebooks

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/revista.io#12]
Agregar soporte a binder [1]

[1] https://mybinder.org/

**Comment by relopezbriega** [comment]
Se agregar link que se genera al final de cada artículo para ejecutar el notebook en mybinder. Los requirements de los notebooks se encuentra dentro de la carpeta binder.

Para que se habilite el link hay que incluir el label NotebookName en el archivo .md con los datos del artículo en la carpeta content.

Ej:

Title: Introducción al Cálculo con Python
Date: 2018-10-20
Category: Calculo
Tags: python, matematica, calculo, derivada, integral, limite
Author: Raul E. Lopez Briega
Description: Cálculo con python. Qué es el cálculo, historia, funciones, límites, derivadas, integrales, teorema fundamental del cálculo, aplicaciones, ejemplos en python
NotebookName: pyCalculus.ipynb

{% notebook pyCalculus.ipynb cells[2:] %}

**Comment by xmnlab** [comment]
se ve genial @relopezbriega ! gracias!
