### ISSUE TITLE
Definir Menus

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/revista.io#2]
@Caaddss 

poderias verificar quais menús podemos ter inicialmente para a revista?

poderias pesquisar 3 revistas mais ou menos com essa ideia para a gente ter como referencia?

**Comment by xmnlab** [comment]
@cymLP2 vc consegue ajudar nessa issue?

a ideia é buscar 3 revistas online mais ou menos parecida com o que estamos fazendo .. uma revista informativa sobre computação científica, com um ar de comunidade também e ver quais são os menus da página ... assim podemos saber o que seria bom ter em nossa página, como: Contato, Sobre nós/revista, categorias, noticias, tweets, etc

**Comment by Caaddss** [comment]
Acho que deve ter um Sobre nós(revista)
Contato
Como submeter um trabalho
Quero ajudar
Tags

**Comment by Caaddss** [comment]
inicialmente acho que podemos trabalhar nessas @xmnlab o que acha?
acho que podemos pensar em como montar um guiazinho do tipo "Gostei, quero um scipy na minha região, como posso organizar?"

e colocar isso no menu, e a partir disso ter uma aba conferências

**Comment by xmnlab** [comment]
me parece uma ótima ideia!!!

**Comment by Caaddss** [comment]
vou abrir uma issue pra gente trabalhar nisso e fechar essa
