### ISSUE TITLE
Definir tags

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/revista.io#3]
@Caaddss 

poderias escrever um texto definindo as tags iniciais para a gente fazer a segmentação dos posts?

podemos ter por áreas .. talvez inicialmente podemos ter as mesmas descritas em:

http://scipyla.org/conf/2017/  > Programas  > Talleres

Além disso creio que vamos precisar de uma tag para cada tipo artículo (comunidade, patrocinadores, etc) e tag em português e espanhol, dependendo do idioma principal do artigo

**Comment by Caaddss** [comment]
@xmnlab 
Machine Learning/Aprendizado de Máquina
Economia
Bioinformática
Física
Química
Linguagem
Ciências Sociais
Ciências da Terra
Eletrica

**Comment by Caaddss** [comment]
Eu ia traduzir, mas vamos ver o q vcs acham antes

**Comment by xmnlab** [comment]
@Caaddss Me parece ótimo! Talvez sería bom adicionar um item mais chamado comunidade

**Comment by Caaddss** [comment]
@xmnlab Comunidades relacionadas a data Science?

**Comment by xmnlab** [comment]
@Caaddss creo que puede ser comunidades python científico / data science

**Comment by Caaddss** [comment]
Perfeito, então fica assim as tags:

Aprendizado de Máquina
Bioinformática
Ciências Sociais/Humanidades(Jornalismo de dados...)
Ciências da Terra
Comunidades (Python Científico/ data Science)
Economia
Elétrica/(Automação)
Física
Linguagem
Química

Podemos fechar nessas por enquanto???

**Comment by xmnlab** [comment]
super! está ótimo! obrigado @Caaddss !
